# Generated by Django 5.2.5 on 2025-10-15 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pasajero')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('empresa_trabajo', models.CharField(max_length=45, verbose_name='Empresa de Trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Ubicacion')),
                ('tipo_parada', models.CharField(choices=[('M', 'Metro'), ('E', 'Empresa'), ('H', 'Hotel'), ('A', 'Aeropuerto'), ('P', 'Paradero'), ('O', 'Otro')], max_length=1, verbose_name='Tipo de Parada')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del Lugar')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion del Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Vehiculo')),
                ('patente', models.CharField(max_length=7, unique=True, verbose_name='Patente')),
                ('marca', models.CharField(max_length=45, verbose_name='Marca')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('M', 'Mantenimiento'), ('E', 'En Ruta')], default='A', max_length=1, verbose_name='Estado')),
                ('revision_tecnica', models.DateField(verbose_name='Revision Tecnica')),
                ('proxima_revision', models.DateField(verbose_name='Proxima Revision')),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id_chofer', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Chofer')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('tipo_licencia', models.CharField(choices=[('A', 'Licencia Clase A'), ('B', 'Licencia Clase B'), ('C', 'Licencia Clase C'), ('D', 'Licencia Clase D'), ('E', 'Licencia Clase E')], max_length=1, verbose_name='Tipo de Licencia')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('fecha_ultimo_control', models.DateField(verbose_name='Fecha Ultimo Control')),
                ('fecha_proximo_control', models.DateField(verbose_name='Fecha Proximo Control')),
                ('id_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RouteAnvil.vehiculo', verbose_name='Vehiculo Asignado')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Viaje')),
                ('fecha', models.DateField(verbose_name='Fecha del Viaje')),
                ('hora_Salida', models.TimeField(verbose_name='Hora de Salida')),
                ('hora_Llegada', models.TimeField(verbose_name='Hora de Llegada')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_destino', to='RouteAnvil.ubicacion', verbose_name='Destino')),
                ('id_chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.chofer', verbose_name='Chofer')),
                ('id_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RouteAnvil.vehiculo', verbose_name='Vehiculo')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_origen', to='RouteAnvil.ubicacion', verbose_name='Origen')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero_Viaje',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Reserva')),
                ('id_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.pasajero', verbose_name='Pasajero')),
                ('id_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.viaje', verbose_name='Viaje')),
            ],
        ),
    ]
