# Generated by Django 5.2.5 on 2025-12-01 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('RouteAnvil', '0001_initial'), ('RouteAnvil', '0002_alter_parada_direccion_alter_parada_nombre'), ('RouteAnvil', '0003_grupo_pasajeros_fecha_hora_deseada_and_more'), ('RouteAnvil', '0004_alter_grupo_pasajeros_fecha_hora_deseada'), ('RouteAnvil', '0005_grupo_pasajeros_tipo_hora_deseada'), ('RouteAnvil', '0006_alter_grupo_pasajeros_tipo_hora_deseada'), ('RouteAnvil', '0007_remove_viaje_hora_llegada_remove_viaje_hora_salida_and_more'), ('RouteAnvil', '0008_chofer_user'), ('RouteAnvil', '0009_viaje_distancia_total_metros_viaje_polyline')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id_chofer', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Chofer')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('tipo_licencia', models.CharField(choices=[('A1', 'Licencia Clase A1'), ('A2', 'Licencia Clase A2'), ('A3', 'Licencia Clase A3'), ('A4', 'Licencia Clase A4'), ('A5', 'Licencia Clase A5'), ('B', 'Licencia Clase B')], max_length=2, verbose_name='Tipo de Licencia')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('fecha_ultimo_control', models.DateField(verbose_name='Fecha Ultimo Control')),
                ('fecha_proximo_control', models.DateField(verbose_name='Fecha Proximo Control')),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id_ubicacion', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Ubicación')),
                ('nombre', models.CharField(max_length=90, verbose_name='Nombre del Lugar')),
                ('tipo_parada', models.CharField(choices=[('X', 'Autocompletar'), ('M', 'Metro'), ('E', 'Empresa'), ('H', 'Hotel'), ('A', 'Aeropuerto'), ('P', 'Paradero'), ('O', 'Otro')], max_length=1, verbose_name='Tipo de Parada')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección del Lugar')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Vehiculo')),
                ('patente', models.CharField(max_length=7, unique=True, verbose_name='Patente')),
                ('marca', models.CharField(max_length=45, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=45, verbose_name='Modelo')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('M', 'Mantenimiento'), ('E', 'En Ruta')], default='A', max_length=1, verbose_name='Estado')),
                ('revision_tecnica', models.DateField(verbose_name='Revision Tecnica')),
                ('proxima_revision', models.DateField(verbose_name='Proxima Revision')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Pasajero')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('empresa_trabajo', models.CharField(max_length=45, verbose_name='Empresa de Trabajo')),
                ('paradero_deseado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradero_deseado', to='RouteAnvil.parada', verbose_name='Paradero deseado')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Pasajeros',
            fields=[
                ('id_grupo_pasajeros', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Reserva')),
                ('estado_creacion_viaje', models.CharField(choices=[('0', 'Estado NULO'), ('1', 'Seleccionando Pasajeros'), ('2', 'Seleccionando Choferes'), ('3', 'Confirmando Viaje'), ('A', 'Viajes Creados')], default='0', max_length=1, verbose_name='Estado de creacion')),
                ('chofer', models.ManyToManyField(blank=True, to='RouteAnvil.chofer', verbose_name='Choferes')),
                ('pasajero', models.ManyToManyField(blank=True, to='RouteAnvil.pasajero', verbose_name='Pasajeros')),
                ('fecha_hora_deseada', models.DateTimeField(blank=True)),
                ('tipo_viaje', models.CharField(choices=[('IDA', 'Ida - Recoger pasajeros'), ('VUELTA', 'Vuelta - Dejar pasajeros')], default='IDA', max_length=10)),
                ('tipo_hora_deseada', models.CharField(choices=[('LLEGADA', 'Hora finalización de viaje'), ('INICIO', 'Hora inicio de viaje')], default='INICIO', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='chofer',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RouteAnvil.vehiculo', verbose_name='Vehiculo Asignado'),
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_viaje', models.CharField(choices=[('IDA', 'Ida - Recoger pasajeros'), ('VUELTA', 'Vuelta - Dejar pasajeros')], default='IDA', max_length=10)),
                ('hora_Salida', models.TimeField()),
                ('hora_Llegada', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.chofer')),
                ('id_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='RouteAnvil.grupo_pasajeros')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.vehiculo')),
                ('punto_encuentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_punto_encuentro', to='RouteAnvil.parada')),
                ('hora_llegada_temp', models.DateTimeField(blank=True, null=True)),
                ('hora_salida_temp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero_Viaje',
            fields=[
                ('id_reserva', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Reserva')),
                ('id_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.pasajero', verbose_name='Pasajero')),
                ('id_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.viaje', verbose_name='Viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Parada_Viaje',
            fields=[
                ('id_parada_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('pasajeros_suben', models.IntegerField(default=0)),
                ('pasajeros_bajan', models.IntegerField(default=0)),
                ('hora_estimada_llegada', models.TimeField(blank=True, null=True)),
                ('id_parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.parada')),
                ('id_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_viaje', to='RouteAnvil.viaje')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('id_viaje', 'orden')},
            },
        ),
        migrations.RunSQL(
            sql='\n                UPDATE "RouteAnvil_viaje"\n                SET "hora_llegada_temp" = CURRENT_DATE + "hora_Llegada"\n                WHERE "hora_Llegada" IS NOT NULL;\n                \n                UPDATE "RouteAnvil_viaje"\n                SET "hora_salida_temp" = CURRENT_DATE + "hora_Salida"\n                WHERE "hora_Salida" IS NOT NULL;\n            ',
            reverse_sql='',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='hora_Llegada',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='hora_Salida',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='hora_llegada_temp',
            new_name='hora_llegada',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='hora_salida_temp',
            new_name='hora_salida',
        ),
        migrations.AlterField(
            model_name='grupo_pasajeros',
            name='tipo_hora_deseada',
            field=models.CharField(choices=[('LLEGADA', 'Hora finalización de viaje'), ('INICIO', 'Hora inicio de viaje')], default='LLEGADA', max_length=10),
        ),
        migrations.AddField(
            model_name='parada_viaje',
            name='hora_estimada_llegada_temp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(
            sql='\n                UPDATE "RouteAnvil_parada_viaje"\n                SET "hora_estimada_llegada_temp" = CURRENT_DATE + "hora_estimada_llegada"\n                WHERE "hora_estimada_llegada" IS NOT NULL;\n            ',
            reverse_sql='',
        ),
        migrations.RemoveField(
            model_name='parada_viaje',
            name='hora_estimada_llegada',
        ),
        migrations.RenameField(
            model_name='parada_viaje',
            old_name='hora_estimada_llegada_temp',
            new_name='hora_estimada_llegada',
        ),
        migrations.AddField(
            model_name='chofer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chofer', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='distancia_total_metros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
