# Generated by Django 5.2.5 on 2025-10-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id_chofer', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Chofer')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('tipo_licencia', models.CharField(choices=[('A', 'Licencia Clase A'), ('B', 'Licencia Clase B'), ('C', 'Licencia Clase C'), ('D', 'Licencia Clase D'), ('E', 'Licencia Clase E')], max_length=1, verbose_name='Tipo de Licencia')),
                ('direccion', models.CharField(max_length=45, verbose_name='Direccion')),
                ('fecha_ultimo_control', models.DateField(verbose_name='Fecha Ultimo Control')),
                ('fecha_proximo_control', models.DateField(verbose_name='Fecha Proximo Control')),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Destino')),
                ('nombre_destino', models.CharField(max_length=45, verbose_name='Nombre Destino')),
                ('comuna', models.CharField(max_length=45, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id_origen', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Origen')),
                ('nombre_origen', models.CharField(max_length=45, verbose_name='Nombre Origen')),
                ('comuna', models.CharField(max_length=45, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Pasajero')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('empresa_trabajo', models.CharField(max_length=45, verbose_name='Empresa de Trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Vehiculo')),
                ('patente', models.CharField(max_length=7, unique=True, verbose_name='Patente')),
                ('marca', models.CharField(max_length=45, verbose_name='Marca')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('M', 'Mantenimiento'), ('E', 'En Ruta')], default='A', max_length=1, verbose_name='Estado')),
                ('revision_tecnica', models.DateField(verbose_name='Revision Tecnica')),
                ('proxima_revision', models.DateField(verbose_name='Proxima Revision')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Viaje')),
                ('fecha', models.DateField(verbose_name='Fecha del Viaje')),
                ('hora_Salida', models.DateTimeField(verbose_name='Hora de Salida')),
                ('hora_Llegada', models.DateTimeField(verbose_name='Hora de Llegada')),
                ('id_chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.chofer', verbose_name='Chofer')),
                ('id_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.destino', verbose_name='Destino')),
                ('id_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.origen', verbose_name='Origen')),
                ('id_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.vehiculo', verbose_name='Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Reserva')),
                ('id_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.pasajero', verbose_name='Pasajero')),
                ('id_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.viaje', verbose_name='Viaje')),
            ],
        ),
    ]
