# Generated by Django 5.2.5 on 2025-11-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección del Lugar'),
        ),
        migrations.AlterField(
            model_name='parada',
            name='nombre',
            field=models.CharField(max_length=90, verbose_name='Nombre del Lugar'),
        ),
    ]
