# Generated by Django 5.2.5 on 2025-10-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0002_vehiculo_anio_vehiculo_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='tipo_licencia',
            field=models.CharField(choices=[('A1', 'Licencia Clase A1'), ('A2', 'Licencia Clase A2'), ('A3', 'Licencia Clase A3'), ('A4', 'Licencia Clase A4'), ('A5', 'Licencia Clase A5'), ('B', 'Licencia Clase B')], max_length=2, verbose_name='Tipo de Licencia'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(default=1, verbose_name='Año'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(default=1, max_length=45, verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
