# Generated by Django 5.2.5 on 2025-11-19 23:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0002_alter_parada_direccion_alter_parada_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_pasajeros',
            name='fecha_hora_deseada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo_pasajeros',
            name='tipo_viaje',
            field=models.CharField(choices=[('IDA', 'Ida - Recoger pasajeros'), ('VUELTA', 'Vuelta - Dejar pasajeros')], default='IDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='grupo_pasajeros',
            name='pasajero',
            field=models.ManyToManyField(blank=True, to='RouteAnvil.pasajero', verbose_name='Pasajeros'),
        ),
    ]
