# Generated by Django 5.2.5 on 2025-10-23 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0003_alter_chofer_tipo_licencia_alter_vehiculo_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fecha',
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion del Viaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de modificación del Viaje'),
        ),
    ]
