# Generated by Django 5.2.5 on 2025-11-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0003_grupo_pasajeros_fecha_hora_deseada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_pasajeros',
            name='fecha_hora_deseada',
            field=models.DateTimeField(blank=True),
        ),
    ]
