# Generated by Django 5.2.5 on 2025-11-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0004_alter_grupo_pasajeros_fecha_hora_deseada'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_pasajeros',
            name='tipo_hora_deseada',
            field=models.CharField(choices=[('INICIO', 'Hora inicio de viaje'), ('LLEGADA', 'Hora finalización de viaje')], default='INICIO', max_length=10),
        ),
    ]
