# Generated by Django 5.2.5 on 2025-10-23 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0004_remove_viaje_fecha_viaje_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_modificacion',
        ),
        migrations.CreateModel(
            name='Grupo_Pasajeros',
            fields=[
                ('id_grupo_pasajeros', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Reserva')),
                ('id_pasajero', models.ManyToManyField(to='RouteAnvil.pasajero', verbose_name='Pasajeros')),
            ],
        ),
    ]
