# Generated by Django 5.2.5 on 2025-11-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0005_grupo_pasajeros_tipo_hora_deseada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_pasajeros',
            name='tipo_hora_deseada',
            field=models.CharField(choices=[('LLEGADA', 'Hora finalización de viaje'), ('INICIO', 'Hora inicio de viaje')], default='INICIO', max_length=10),
        ),
    ]
