# Generated by Django 5.2.5 on 2025-10-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0005_remove_viaje_fecha_modificacion_grupo_pasajeros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_pasajeros',
            name='id_grupo_pasajeros',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Reserva'),
        ),
    ]
