# Generated by Django 5.2.5 on 2025-11-27 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0006_alter_grupo_pasajeros_tipo_hora_deseada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='hora_Llegada',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='hora_Salida',
        ),
        migrations.AlterField(
            model_name='grupo_pasajeros',
            name='tipo_hora_deseada',
            field=models.CharField(choices=[('LLEGADA', 'Hora finalización de viaje'), ('INICIO', 'Hora inicio de viaje')], default='LLEGADA', max_length=10),
        ),
        migrations.AlterField(
            model_name='parada_viaje',
            name='hora_estimada_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_llegada',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='hora_salida',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
