# Generated by Django 5.2.5 on 2025-10-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0006_alter_grupo_pasajeros_id_grupo_pasajeros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo_pasajeros',
            old_name='id_pasajero',
            new_name='pasajero',
        ),
    ]
