# Generated by Django 5.2.5 on 2025-11-27 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0007_remove_viaje_hora_llegada_remove_viaje_hora_salida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chofer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chofer', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
