# Generated by Django 5.2.5 on 2025-10-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0007_rename_id_pasajero_grupo_pasajeros_pasajero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={'verbose_name': 'Chofer', 'verbose_name_plural': 'Choferes'},
        ),
    ]
