# Generated by Django 5.2.5 on 2025-11-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0008_chofer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='distancia_total_metros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
