# Generated by Django 5.2.5 on 2025-10-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0008_alter_chofer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_pasajeros',
            name='chofer',
            field=models.ManyToManyField(blank=True, to='RouteAnvil.chofer', verbose_name='Choferes'),
        ),
    ]
