# Generated by Django 5.2.5 on 2025-10-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0009_grupo_pasajeros_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_pasajeros',
            name='estado_creacion_viaje',
            field=models.CharField(choices=[('0', 'Estado NULO'), ('1', 'Seleccionando Pasajeros'), ('2', 'Seleccionando Choferes'), ('3', 'Confirmando Viaje'), ('A', 'Viajes Creados')], default='0', max_length=1, verbose_name='Estado de creacion'),
        ),
    ]
