# Generated by Django 5.2.5 on 2025-11-03 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0010_grupo_pasajeros_estado_creacion_viaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id_ubicacion', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID Ubicación')),
                ('tipo_parada', models.CharField(choices=[('M', 'Metro'), ('E', 'Empresa'), ('H', 'Hotel'), ('A', 'Aeropuerto'), ('P', 'Paradero'), ('O', 'Otro')], max_length=1, verbose_name='Tipo de Parada')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre del Lugar')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección del Lugar')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
            ],
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_destino', to='RouteAnvil.parada', verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes_origen', to='RouteAnvil.parada', verbose_name='Origen'),
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
