# Generated by Django 5.2.5 on 2025-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0011_parada_alter_viaje_destino_alter_viaje_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parada',
            name='tipo_parada',
            field=models.CharField(choices=[('X', 'Autocompletar'), ('M', 'Metro'), ('E', 'Empresa'), ('H', 'Hotel'), ('A', 'Aeropuerto'), ('P', 'Paradero'), ('O', 'Otro')], max_length=1, verbose_name='Tipo de Parada'),
        ),
    ]
