# Generated by Django 5.2.5 on 2025-11-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0012_alter_parada_tipo_parada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='paradero_deseado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradero_deseado', to='RouteAnvil.parada', verbose_name='Paradero deseado'),
        ),
    ]
