# Generated by Django 5.2.5 on 2025-11-14 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0013_pasajero_paradero_deseado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='origen',
        ),
        migrations.AddField(
            model_name='viaje',
            name='punto_encuentro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='viajes_punto_encuentro', to='RouteAnvil.parada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='tipo_viaje',
            field=models.CharField(choices=[('IDA', 'Ida - Recoger pasajeros'), ('VUELTA', 'Vuelta - Dejar pasajeros')], default='IDA', max_length=10),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='hora_Llegada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='hora_Salida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id_chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.chofer'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id_vehiculo',
            field=models.ForeignKey(default='cf4570a717a941ba8be11b802622298e', on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.vehiculo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='id_viaje',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Parada_Viaje',
            fields=[
                ('id_parada_viaje', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('pasajeros_suben', models.IntegerField(default=0)),
                ('pasajeros_bajan', models.IntegerField(default=0)),
                ('hora_estimada_llegada', models.TimeField(blank=True, null=True)),
                ('id_parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RouteAnvil.parada')),
                ('id_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas_viaje', to='RouteAnvil.viaje')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('id_viaje', 'orden')},
            },
        ),
    ]
