# Generated by Django 5.2.5 on 2025-11-14 02:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteAnvil', '0014_remove_viaje_destino_remove_viaje_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='id_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='RouteAnvil.grupo_pasajeros'),
        ),
    ]
